name: Quality

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/install

      - name: Build packages
        run: pnpm build

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/install

      - name: Run tests
        run: pnpm test

  oxlint:
    name: Oxlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/install

      - name: Run oxlint
        run: pnpm lint

  types:
    name: TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/install

      - name: Run typecheck
        run: pnpm typecheck

  oxfmt:
    name: Oxfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/install

      - name: Run oxfmt check
        run: pnpm format:check
